Hw 1
darya-startsava/react-task pull request #1
Opened 2022-12-11 20:25 UTC by darya-startsava

Task description: Form layout made with stateless class components.
Deploy: https://darya-startsava.github.io/react-task/
Screenshot:
![image](https://user-images.githubusercontent.com/86919538/206926951-bc7d7724-f9df-4d20-8291-30e0cdb90dd3.png)

2022-12-12 09:32 UTC, polina-ivanova reviewed
Good job, it was really useful to review your code. Fix one remark, and I approve.

2022-12-12 09:32 UTC, polina-ivanova commented on src/App.js
>  function App() {
Change to a class component, please. We should use class components in this homework

2022-12-12 13:20 UTC, darya-startsava commented on src/App.js
>  function App() {
done

2022-12-12 13:25 UTC, polina-ivanova approved these changes

2022-12-14 19:08 UTC, poulkud requested changes

2022-12-14 19:08 UTC, poulkud commented on src/App.js
> +    <>
а зачем тут тернарник?

2022-12-14 19:08 UTC, poulkud commented on src/components/button/Button.jsx
> +      <button className={`button ${appearance}`}>{children}</button>
круто!

2022-12-14 19:08 UTC, poulkud commented on src/components/form/Form.jsx
> +          <InputText label={"Имя"} placeholder={"Имя"} />
в целом ок, но подумай над тем чтобы например в константе хранились данные и рендерились через мап нужные компоненты

2022-12-14 19:08 UTC, poulkud commented on src/components/inputDate/InputDate.jsx
> +      <label>{label}<input className="input_date" type="date" placeholder={placeholder} /></label>
попробуй объединить инпуты, чтобы через пропс просто кидались в один компонент разные варианты отрисовки и типа, для обычного инпута и даты

2022-12-15 12:04 UTC, darya-startsava commented on src/App.js
> +    <>
fixed

2022-12-15 13:24 UTC, darya-startsava commented on src/components/form/Form.jsx
> +          <InputText label={"Имя"} placeholder={"Имя"} />
fixed

2022-12-15 13:24 UTC, darya-startsava commented on src/components/inputDate/InputDate.jsx
> +      <label>{label}<input className="input_date" type="date" placeholder={placeholder} /></label>
fixed

2022-12-18 17:36 UTC, polina-ivanova approved these changes

2022-12-20 19:10 UTC, poulkud approved these changes

2022-12-21 12:19 UTC, merged